services:
  fnauthz:
    image: fonoster/fnauthz:latest
    restart: unless-stopped
    environment:
      FNAUTHZ_STRIPE_SECRET_KEY: ${FNAUTHZ_STRIPE_SECRET_KEY}
      FNAUTHZ_INFLUXDB_URL: ${FNAUTHZ_INFLUXDB_URL}
      FNAUTHZ_INFLUXDB_TOKEN: ${FNAUTHZ_INFLUXDB_TOKEN}
      FNAUTHZ_LOGS_LEVEL: ${FNAUTHZ_LOGS_LEVEL}
      FNAUTHZ_LOGS_TRANSPORT: ${FNAUTHZ_LOGS_TRANSPORT}
      FNAUTHZ_LOGS_FORMAT: ${FNAUTHZ_LOGS_FORMAT}
      FNAUTHZ_NATS_URL: ${FNAUTHZ_NATS_URL}
      IDENTITY_DATABASE_URL: ${FNAUTHZ_IDENTITY_DATABASE_URL}
      CLOAK_ENCRYPTION_KEY: ${FNAUTHZ_CLOAK_ENCRYPTION_KEY}
    expose:
      - 50071:50071
