services: 
  fnauthz:
    image: fonoster/fnauthz:latest
    restart: unless-stopped
    environment:
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      IDENTITY_DATABASE_URL: ${IDENTITY_DATABASE_URL}
      CLOAK_ENCRYPTION_KEY: ${CLOAK_ENCRYPTION_KEY}
      LOGS_LEVEL: ${LOGS_LEVEL}
      LOGS_TRANSPORT: ${LOGS_TRANSPORT}
    expose:
      - 50071:50071
